:imagesdir: ../assets/images

= Module 2: Design the Internal Developer Portal

include::style.adoc[]

== Overview

{product_name_rhdh} is based on the https://backstage.io/[Backstage] framework for building internal developer portals. This project was donated to the https://www.cncf.io/projects/backstage/[CNCF] by Spotify in 2020. Platform engineers can use {product_name_rhdh} to build internal developer portals. Doing so involves integrating with various data sources, catalog existing software components, infrastructure, and resources, configuring single sign-on, and more.

In this module you'll learn how to architect, install, and bootstrap an instance of {product_name_rhdh} to create a minimum viable internal developer portal for a select group of developers within your organization.

The initial use cases for your developer portal are:

* Self-service discovery of software components and dependencies.
* Visibility into CI/CD pipelines.
* Hosting documentation.
* Scaffolding projects that adhere to organizational best practices.

== Module Objectives

Satisfying the previously defined use cases involves configuring {product_name_rhdh} to integrate with your existing platforms, tools, and infrastructure. For example, if your organization uses OpenShift Pipelines for continuous integration, you'll need to configure the {product_name_rhdh} instance with the appropriate integration to fetch and display data from the an OpenShift cluster used to perform https://tekton.dev/docs/pipelines/pipelineruns/[Pipeline Runs].

It could be said that the value of an internal developer portal is proportional to the thought and energy invested into it by the platform engineer(s), and developers using it.

In this module you'll:

* Identify the platform requirements and dependencies, such as single sign-on (SSO), source code management (SCM), RBAC, resources, existing assets
* Integrate {product_name_rhdh} with the dependant services, such as GitLab and Keycloak
* Learn about https://backstage.io/docs/features/software-catalog/[Backstage Entities], e.g Components, APIs, and Docs
* Ready for developer onboarding

== Workshop Environment

Your workshop environment has been preconfigured with the following software and platform components:

* Red Hat Build of Keycloak
* OpenShift GitOps
* OpenShift Pipelines
* GitLab

For the purposes of this workshop, we'll assume that your organization has standardized on these tools, and it's your objective as the platform engineer to integrate them with {product_name_rhdh}.

For convenience, {product_name_rhdh} has been predeployed via OpenShift GitOps using the official https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/installing_red_hat_developer_hub_on_openshift_container_platform/assembly-install-rhdh-ocp-helm[{product_name_rhdh} Helm Chart].

Helpful links:

* OpenShift GitOps 

TODO: Add note about the existing Argo CD application and link to the configuration repository in GitLab. Provide an overview of 

.Click to view the lab environment details
[%collapsible]
====
include::env.adoc[]
====

== Introductions to Concepts

{product_name_rhdh}, and internal developer hubs in general, can be thought of as a modular systems where you aggregate and display data related to the software within an organization.

The core features of {product_name_rhdh} are the:

* Software Catalog
* Software Templates
* TechDocs
* Kubernetes Integration

=== Software Templates

Software Templates have been referred to as "Golden Paths" in the past. These templates are designed and curated by platform engineers to provide a starting point for new software components that adhere to best practices within an organization. Templates can also be used to patch and update existing source code repositories.

=== Software Catalog

The Software Catalog is a centralised asset tracker for all of the software in your organization. It stores and tracks *Entities*:

* Components: Units of software, e.g microservices, websites, libraries.
* Resources: Databases, S3 buckets, brokers.
* APIs: Represent interfaces such as REST, gRPC, and GraphQL APIs.
* Systems: Collections of Components that make up an application or platform.
* Domains: A higher-level grouping of Systems and Entities.
* User: Individual users that are part of your organization.  
* Group: Groups of Users.

Users and Groups can be specified as owners of other Entities. If this seems abstract, don't worry, you'll see it in definitive terms shortly. 

=== Understanding the {product_name_rhdh} Configuration

Upstream Backstage uses an https://backstage.io/docs/conf/[app-config.yaml] file to define configuration values, and {product_name_rhdh} is no different.

A simple Backstage configuration file looks similar to the following example:

```yaml
# Define authentication configuration
auth:
  environment: production
  providers:
    oidc:
      production:
        # Keys with values wrapped in ${} syntax instruct Backstage to read
        # those values from an environment variable with the given name
        metadataUrl: ${OAUTH_REALM_URL}/.well-known/openid-configuration
        clientId: ${OAUTH_CLIENT_ID}
        clientSecret: ${OAUTH_CLIENT_ID}

# Tells Backstage to serve the OIDC sign in page        
signInPage: oidc      

# Static configuration for the software catalog. Can be used to import
# entities on startup, and define the allowed entity types.
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: https://github.com/someorg/somerepo/import-me.yaml

# A configuration for the TechDocs plugin. This example instructs the plugin to
# build documentation at runtime, instead of pulling prebuilt HTML from S3
techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local
```

Since you're using the {product_name_rhdh} Helm Chart to install and manage your internal developer portal, your configuration is nested under an `upstream.backstage.appConfig` property. View your configuration by visiting your https://gitlab-gitlab.{openshift_cluster_ingress_domain}rhdh/developer-hub-config/-/blob/main/values.yaml[rhdh/developer-hub-config repository on GitLab].

Your configuration in GitLab is continuously monitored and deployed using the https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}/applications[Backstage Application in OpenShift GitOps] (login using `admin` and the password found in the https://console-openshift-console.{openshift_cluster_ingress_domain}/k8s/ns/openshift-gitops/secrets/openshift-gitops-cluster[openshift-gitops-cluster Secret]).

== Activity: Authentication

{product_name_rhdh} supports four authentication providers:

* Guest (suitable for experimentation and demos only)
* OpenID Connect
* GitHub
* Microsoft Azure

In this activity you'll configure an OpenID Connect authentication provider. In this environment, your users are sourced from GitLab and the Red Hat Build of Keycloak is used as the identity broker between {product_name_rhdh} and your GitLab instance.

TODO DIAGRAM SHOWING AUTH FLOW

=== High-Level Workflow

A complete set of documentation for configuring OpenID Connect authentication using Red Hat Single-Sign On is available in the https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html-single/authentication/index#enabling-authentication-with-rhsso[{product_name_rhdh} documentation]. 

The high-level steps involve:

NOTE: Don't worry if some of the following bullet points are hard to understand upon first reading them. You'll be guided through each step-by-step.

. Configuring the Keycloak Backstage plugin to synchronize users from Red Hat Single-Sign On to {product_name_rhdh}.
. Creating a Realm in Red Hat Single-Sign On. This has been pre-configured for you. View using the following URL and credentials:
    * *URL*: https://sso.{openshift_cluster_ingress_domain}
    * *Credentials*: https://console-openshift-console.{openshift_cluster_ingress_domain}/k8s/ns/keycloak/secrets/keycloak-initial-admin[View on OpenShift]
. Configuring the `oidc` {product_name_rhdh} authentication provider with the Realm details.
. Setting `oidc` as `signInPage` page type for {product_name_rhdh}.
. Enabling session support on {product_name_rhdh}.

=== Synchronize Users to the Software Catalog

In prior sections we discussed the Software Catalog, and the User Entity. Generally speaking, if a user is logging into your IDP, you want a User Entity that corresponds to that user's identity to be represented in the Software Catalog.

Plugins can be used to synchronize the users in your organization's identity and access management solution to the Software Catalog as User entities. In your workshop environment you'll achieve this using the https://www.npmjs.com/package/@backstage-community/plugin-catalog-backend-module-keycloak[@backstage-community/plugin-catalog-backend-module-keycloak (formerly @janus-idp/backstage-plugin-keycloak-backend-dynamic)].

Here's how to do it:

. Visit your https://gitlab-gitlab.{openshift_cluster_ingress_domain}rhdh/developer-hub-config/[rhdh/developer-hub-config repository on GitLab].
. Locate the `global.dynamic.plugins` entry in the YAML. 
. Modify the configuration so that the Keycloak plugin's `disabled` value is set to `false`.

Dynamic plugin loading is a value added feature included in {product_name_rhdh} that's currently unavailable in upstream Backstage - you can read more about it in the https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/introduction_to_plugins/con-rhdh-plugins#con-rhdh-plugins[{product_name_rhdh} documentation].

Next, configure the plugin:

. Locate the `global.upstream.backstage.catalog.providers.keycloakOrg` entry in the YAML.
. Uncomment the entire configuration.
. Commit your changes.

After the changes are committed visit and Refresh the https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}/applications[Backstage Application in OpenShift GitOps]. This will trigger a rollout of {product_name_rhdh}. Once the rollout is complete view logs from the *developer-hub* Pod, and filter for lines containing "keycloak"; you should find a line stating that a number of entities were synchronized into the Software Catalog.

TODO: add screenshots and steps to login and view users using Guest authentication

=== Enable OpenID Connect Authentication

. Visit your https://gitlab-gitlab.{openshift_cluster_ingress_domain}rhdh/developer-hub-config/[rhdh/developer-hub-config repository on GitLab].
. Open the *values.yaml* file, then select *Edit > Edit single file*.
. Locate the `upstream.backstage.appConfig.auth` object in the YAML; it is commented out.
. Uncomment the configuration.

This is an example standard Backstage `auth` configuration. Here's a summary of what this configuration specifies:

. Enable sessions, and use the `BACKEND_SECRET` environment variable to sign sessions.
. Set the authentication `environment` to `production`. Environments can have any arbitrary name.
. Enable the OpenID Connect provider (`providers.oidc`) with the following configuration:
    * Provide a `production` configuration (corresponding to the `environment` defined previously).
    * Use the `backstage' Realm (`metadataUrl`).
    * Load the `clientId` and `clientSecret` from environment variables (loaded from the precreated `oauth-client` Secret specified in `extraEnvVarsSecrets`)
    * Map any signing in user identity to a a User Entity in {product_name_rhdh} using the specified https://backstage.io/docs/auth/identity-resolver/[resolver].

Next, uncomment the `signInPage`. This property is specific to {product_name_rhdh}. It ensures the correct sign in UI is rendered. In upstream Backstage this requires React code changes.

== Activity 2

== Conclusion