:imagesdir: ../assets/images


= Module 4: Setup Developer Sandbox

include::style.adoc[]


== Overview

Red Hat Developer Hub has been setup, and taken for a test drive too. The next steps is to onboard existing projects and applications so that the developer teams can access them through one plane of glass. 

In this section, we will shadow the platform team 

. setting up a Software Template to onboard existing applications
. import existing applications
. enabling auto-discovery of components

And right after that, we will shadow an App Developer use all these tools to accelerate their developer process

== Objectives

* Developer is assigned the task of enhancing an existing application
* PE onboards  existing app (all the components, APIs etc) on Dev cluster through RHDH
* Development commences in dev local environment. Checks is Dependency Analyzer is clear of CVEs.
* Once code is ready, Developer issues a PR from the feature branch of their fork to the project repo

* More streamlined less ad-hoc approach to application deployment pipelines


== Shadowing the Platform Engineer

=== Software templates to import existing applications

A typical software application consists of source-code, kubernetes manifests and also DevOps entities such as pipelines to help in the CI/CD process. 

The Platform Engineer team focuses on the online web app of Parasol consisting of 

* `parasol-web` online web-app (Node + Angular)
* `parasol-store` core services called parasol-store (Quarkus), and 
* `parasol-db` core database (PostgreSQL)
* `parasol-api` (OpenAPI Spec)

Developer Hub identifies components based on a `catalog-info.yaml` file in the repository. This file contains details about 

* where the source code is
* how to access the documentation
* who the owners are
* what are the dependencies and dependents etc.

With the right plugins, this `catalog-info.yaml` file can also help to show these critical information in a single pane of glass  within the component itself:

* CI pipelines
* CD deployments
* Git merge statuses
* Cluster details

To make importing a large number of existing applications into Developer Hub possible/feasible, the Platform Engineering (PE) team creates a *Software Template* that can automate both creation of the `catalog-info.yaml` file, and also auto-create `techdocs` skeleton structure.

There are two options in terms of where these files  (Catalog Info and TechDocs) could be stored for these existing software apps.

. The entities can be added to the same Git repositories as the existing source-code repo
. Create an entity which acts like a collection of all of the catalog-info files and TechDocs of the existing code

In this case, so as to not change existing source code, Parasol team goes with the 2nd approach of creating _an *Envelope* of all the `catalog-info.yaml` files_ of the apps.
