:imagesdir: ../assets/images

= Module 4: Accelerate Developer Inner-Loop

include::style.adoc[]

== Overview

Organizations need a way to import existing services, APIs and resources with little impact to the existing components. This module focused on an opinionated way to onboard existing projects and applications so that the developer teams can access them through a single plane of glass. 

Platform Engineering teams can Software Templates which can then be used by developers to import their apps into Developer Hub. The Software template can built intelligent enough to gather details about the component's Source Repo, TechDocs, Pipelines, dependencies, CI/CD,  and various other details which then allows developer teams to accelerate their inner-loop of developing the assigned features and tasks.

== Module Objectives

* Platform Engineers create Software Templates and Integrations to import existing software components from Git
* Developers use these Software Templates to import their existing software components and APIs. 
* Developer is assigned the task of enhancing an existing application, and creates a Git Feature Branch
* Developer used another templates to setup an isolated dev environment based on Feature Branch
* Developer can rapidly develop and view all actions performed right from Developer Hub thereby reducing cognitive load.
* Once code is ready, Developer issues a PR from the feature branch of their fork to the project repo
