:imagesdir: ../../assets/images


= Module 4.1: Introduction to Concepts

include::../style.adoc[]

== Using Software Templates to Import Existing Applications

=== Catalog Info: A Refresher

You've already seen the magic of the `catalog-info.yaml` file. {product_name_rhdh} can identify and import components based on the presence of a `catalog-info.yaml` file in the repository. This file contains:

* Helpful links.
* Ownership information.
* Instructions on where to find the TechDocs.
* Relationships between the Component and other Entities.

With the right plugins, configuration can be added to the `catalog-info.yaml` to show critical information in the Component view on {product_name_rhdh}:

* CI pipelines
* CD deployments
* Git merge statuses
* Cluster details
* API documentation

=== The Approach

To make importing a large number of existing applications into {product_name_rhdh} scalable, the Platform Engineering (PE) team creates a *Software Template* that automates both the creation of the `catalog-info.yaml` file, and auto-creates a TechDocs skeleton structure.

The necessary Catalog Info and TechDocs could be stored in one of two locations for these existing applications:

. The new files can be added to the same Git repository as the existing source-code.
. Alternatively, a new "entity repository" can be created to store a collection of all of the `catalog-info.yaml` and TechDocs files.

In this case, so as to not change existing source code, Parasol team goes with the 2nd approach. This repository will contain a set of https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-location[*Location*, window="content"] files that contain references to other `catalog-info.yaml` files.

{product_name_rhdh} can _auto-discover_ these Location files based on the file names (, e.g an _envelope-*.yaml_ wildcard) across the Git repository. The reason we look for specific file names is to ensure we don't overload Git with multiple queries while performing auto-discovery.

Note: Auto-discovery can be configured with a _schedule_ that defines how often you want it to run. Be judicious with the scheduling frequency so as not to hit API rate limits with your Git hosting provider. https://backstage.io/docs/integrations/github/discovery/[Learn more, window="content"] about GitHub rate limits.


== An Overview of Parasol Application

The Parasol application consists of the following Components:

* `parasol-web` online web-app (Node.js & Angular)
* `parasol-store` core services (Quarkus)
* `parasol-db` core database (PostgreSQL)
* `parasol-api` (OpenAPI Spec)

In the next sections of this module, we will shadow both the Platform Engineers and Developers as they navigate through onboarding existing applications and accelerate the inner-loop leading to increased developer productivity.
